### ISSUE TITLE
Question About Required File In Step 5

### ISSUE THREAD

**Issue by 1667857557** [Marijn-Schipper/FLAMES#2]
Dear Marijn,

Thanks for your excellent work. We want to use this tool with our data. Could you provide more information about the INDEXFILE in step 5 and specify the GENOMIC_LOCI_FILE? We couldn't find the annotated_locus_1.txt file. Could you give us some examples?

Best,
Huang

**Comment by Marijn-Schipper** [comment]
Dear Huang,

There is an example of an indexfile for step 5 [here](https://github.com/Marijn-Schipper/FLAMES/blob/master/example_data/indexfile.txt).
The filename column contains all the credible set files from fine-mapping that we want to run FLAMES on. 
The column Annotfiles contains the corresponding output filenames of each credible set.

FLAMES by default will annotate all genes within 750kb of  the credible set. 
If you want to run FLAMES with predefined loci you can use a  genomic_risk_loci file. This works with the FUMA GenomicRiskLoci.txt or you can create your own file with the columns GenomicLocus, chr, start, end. When you do use genomic risk loci, make sure you add the column GenomicLocus to the corresponding files in the indexfile, so that FLAMES knows which credible sets you want linked to which locus. I would however recommend to not predefine your loci and use the standard annotation window of 750kb.

Let me know if you still have any questions or if parts of my explanation were unclear.

**Comment by 1667857557** [comment]
Hi Marijn,

Delighted to see your reply! We ran FLAMES with the following code but unfortunately encountered an error. Attached are the indexfile.txt and one of the credible set files we used. Could you provide some suggestions regarding it? Thanks for your assistance!
[FLAMES.zip](https://github.com/Marijn-Schipper/FLAMES/files/15125215/FLAMES.zip)

Best,
Huang

```
(FLAMES) huang@TNR:/mnt/g/linux/FLAMES$ python3 FLAMES.py annotate \
-o /mnt/g/linux/FLAMES/ \
-a /mnt/g/linux/FLAMES/Annotation_data/ \
-p /mnt/g/linux/FLAMES/A.preds \
-m /mnt/g/linux/FLAMES/A.genes.out \
-mt /mnt/g/linux/FLAMES/tissue_A.gsa.out \
-id /mnt/g/linux/FLAMES/indexfile.txt

*********************************************************************
*Fine-mapped Locus Assesment Model of Effector geneS (FLAMES)
* Version 1.0.0
* (C) 2023 Marijn Schipper
*********************************************************************

Traceback (most recent call last):
  File "FLAMES.py", line 310, in <module>
    main()
  File "FLAMES.py", line 295, in main
    functional_annotation(args)
  File "FLAMES.py", line 125, in functional_annotation
    annotate(
  File "/mnt/g/linux/FLAMES/annotate.py", line 42, in wrapper
    func(*args, **kwargs)
  File "/mnt/g/linux/FLAMES/annotate.py", line 1260, in main
    PoPS = pd.read_csv(pops_out, sep="\t", engine="pyarrow")
  File "/home/huang/anaconda3/envs/FLAMES/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "/home/huang/anaconda3/envs/FLAMES/lib/python3.8/site-packages/pandas/io/parsers.py", line 448, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/home/huang/anaconda3/envs/FLAMES/lib/python3.8/site-packages/pandas/io/parsers.py", line 880, in __init__
    self._make_engine(self.engine)
  File "/home/huang/anaconda3/envs/FLAMES/lib/python3.8/site-packages/pandas/io/parsers.py", line 1121, in _make_engine
    raise ValueError(
ValueError: Unknown engine: pyarrow (valid options are "c", "python", or "python-fwf")
```

**Comment by Marijn-Schipper** [comment]
This errror is thrown if pyarrow is not installed in your python environment.
Did you use the provided conda .yml file or requirements.txt file to create a FLAMES environment?
That should solve the issue. If no errors were thrown during environment creation and you are still experiencing the pyarrow error please let me know and I will try to fix it asap.

**Comment by 1667857557** [comment]
Things have been solved. The problem was that we specified the wrong version of Python. Thanks for your excellent work!

**Comment by lvilarribo9** [comment]
Dear Marijn,

Could you elaborate on why you don't recommend to predefine the loci and use the standard annotation window of 750kb? 

I have run it both ways, but when using predefined loci, some loci do not produce an annotation output file and the subsequent scoring script fails because it expects annotation files that do not exist. Is that the reason why you recommend using the default window?

Thanks a lot!

Laura
